sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mzamith/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mzamith/multi-docker-test npm run test

after_success:
  - docker build -t mzamith/multi-docker-client ./client
  - docker build -t mzamith/multi-docker-nginx ./nginx
  - docker build -t mzamith/multi-docker-server ./server
  - docker build -t mzamith/multi-docker-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mzamith/multi-docker-client
  - docker push mzamith/multi-docker-nginx
  - docker push mzamith/multi-docker-server
  - docker push mzamith/multi-docker-worker